name: heic_to_png_jpg
description: A Flutter package to convert HEIC images to JPG, PNG, or WebP on mobile, web, and desktop platforms.
version: 0.1.2
homepage: https://github.com/IbrahimElmourchidi/heic_to_png_jpg
repository: https://github.com/IbrahimElmourchidi/heic_to_png_jpg

topics:
  - image
  - heic
  - heif
  - converter

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: any
  # image: ^4.0.15
  image:
    git:
      url: git@github.com:flutterdevdomit/image.git
      ref: temp_fork
  heif_converter: any
  path_provider: any
  plugin_platform_interface: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  test: any

platforms:
  android:
  ios:
  web:
  macos:
  windows:
  linux:
